### PR TITLE
treewide: passing autopep8

### PR DESCRIPTION
**Pull request by HitaloM**
Autopep8 is a pypi module that does the automatic formatting of the code following the rules of pep8, I decided to use it in UserLixo and noticed that the code was much cleaner, organized and beautiful.

### CODE REVIEW

**Comment by alissonlauffer** [comment]
This pull request breaks some code semantics:
 - userlixo/\_\_main\_\_.py have its imports not at the top of the code because there is a line where they are automatically installed/updated.

**Comment by HitaloM** [comment]
As I imagined Codacy failed the verification, the reason is that autopep8 only fixed the formatting, so Codacy identified already old errors of the code. 😁

**Comment by HitaloM** [comment]
> This pull request breaks some code semantics:
>  - userlixo/\_\_main\_\_.py have its imports not at the top of the code because there is a line where they are automatically installed/updated.

I imagined it, but the @AndrielFR tested without errors...

**Comment by alissonlauffer** [comment]
> I imagined it, but the @AndrielFR tested without errors...

Try with a clean install without installing requirements first.

**Comment by HitaloM** [comment]
> > I imagined it, but the @AndrielFR tested without errors...
> 
> Try with a clean install without installing requirements first.

I think that's right now.

**Comment by alissonlauffer** [comment]
lgtm

**Comment by usernein** [comment]
No.

**Pull request closed without merging**
