### PR TITLE
config.ini

### PR DESCRIPTION
**Pull request by Sunda001**
added valid api_id and api_hash

### CODE REVIEW

**Comment by alissonlauffer** [comment]
why?

**Comment by Sunda001** [comment]
use it as default

**Comment by alissonlauffer** [comment]
Ok, but users are encouraged to create their own api id/hash.

**Comment by Sunda001** [comment]
yeah they can change it if they want

**Comment by alissonlauffer** [comment]
From what app is that api id/hash?

**Comment by Sunda001** [comment]
IMG_20201204_040133_826

**Comment by usernein** [comment]
I can use it but not in this way.
config.ini is a file listed in .gitignore, it's supposed to be created by the user. If i add a config.ini in the repo, it would conflict when the user edit it.
That's why i initially added a default config file as config.env_example and not as config.env.

What can i do is to remove PYROGRAM_CONFIG in favor of two new env vars: API_ID and API_HASH. Then you'll paste the keys in the setup process, together with BOT_TOKEN.
Doing this, they can have a default value, just like LOGS_CHAT and PREFIXES does

**Comment by Sunda001** [comment]
ah okay then

**Pull request closed without merging**
